### ISSUE TITLE
[Readme] Chat Space

### ISSUE THREAD

**Issue by Nought57** [ExtraCorePE/ExtraCorePE#1]

**Comment by ISRAPIL** [comment]
Hello :)

**Comment by Nought57** [comment]
Hello, uploading src now :)

**Comment by ghost** [comment]
hi

**Comment by ISRAPIL** [comment]
Why can not I change anything in the repository?

**Comment by ghost** [comment]
@Nought57 so fork Tesseract or aother software?

**Comment by QueryPE** [comment]
@Nought57 you should create a gitter chat [here](https://gitter.im/)

**Comment by ISRAPIL** [comment]
Tesseract

**Comment by ISRAPIL** [comment]
Nice

**Comment by ISRAPIL** [comment]
Create me ReadMe?

**Comment by Nought57** [comment]
sure

**Comment by QueryPE** [comment]
https://gitter.im/ExtraCorePE

**Comment by QueryPE** [comment]
we can chat here

**Comment by ghost** [comment]
okey

**Comment by ghost** [comment]
can i be invited @Nought57

**Comment by ISRAPIL** [comment]
Wait a bit @caspervanneck

**Comment by ghost** [comment]
@ISRAPIL okey i will wait ;P

**Comment by Nought57** [comment]
Commit contents are important.

**Comment by ghost** [comment]
@Nought57 okey

**Comment by ghost** [comment]
Why does the gitter not work

**Comment by ISRAPIL** [comment]
Do I need to download the kernel?

**Comment by ghost** [comment]
@QueryPE

**Comment by ghost** [comment]
@ISRAPIL are you linux?

**Comment by ISRAPIL** [comment]
Windows and Linux

**Comment by ISRAPIL** [comment]
Don't create developed soul in files, pls

**Comment by Nought57** [comment]
Adding the initial file is over.
We will make templates and descriptions etc by themselves.

**Comment by ghost** [comment]
why is ther no rooms at gitter ?

**Comment by ISRAPIL** [comment]
Speak Russian, if you can, lol

**Comment by ISRAPIL** [comment]
There are, you probably did not go into the gitter

**Comment by QueryPE** [comment]
I probably need to invite you @caspervanneck

**Comment by ISRAPIL** [comment]
https://gitter.im/ExtraCorePE?source=orgpage @caspervanneck

**Comment by ghost** [comment]
@ISRAPIL it dont work maby setup a discord group

**Comment by QueryPE** [comment]
Did you login to gitter, also I think it could possibly be that your not a member yet

**Comment by Nought57** [comment]
I don't dislike you, I'm a bit worried. 
I was watching the contents of the Commit that was on the your team.
I was also watching branch and others, but that was a bad commit for users.

**Comment by ghost** [comment]
@Nought57 ??

**Comment by ghost** [comment]
@QueryPE  am login to gitter

**Comment by ISRAPIL** [comment]
What? Are you talking about me? @Nought57

**Comment by QueryPE** [comment]
@Nought57 to whom are you speaking about?

**Comment by ghost** [comment]
@QueryPE  @ISRAPIL i tink its about me....

**Comment by ghost** [comment]
and most of groups from me are dead

**Comment by ISRAPIL** [comment]
mmm

**Comment by ISRAPIL** [comment]
Join gitter

**Comment by ghost** [comment]
@ISRAPIL there are no rooms

**Comment by ISRAPIL** [comment]
Loggin in gitter

**Comment by ghost** [comment]
am loggin in to gitter

**Comment by ISRAPIL** [comment]
https://gitter.im/login/github?action=login&source=intro-login

**Comment by QueryPE** [comment]
I believe the gitter is a private one not sure

**Comment by QueryPE** [comment]
Oops lol

**Comment by ghost** [comment]
..

**Comment by ghost** [comment]
@Nought57  you have it obout me ?

**Comment by ISRAPIL** [comment]
https://gitter.im/ExtraCorePE?utm_source=share-link&utm_medium=link&utm_campaign=share-link

**Comment by ISRAPIL** [comment]
https://gitter.im/ExtraCorePE?utm_source=share-link&utm_medium=link&utm_campaign=share-link @caspervanneck

**Comment by QueryPE** [comment]
@ISRAPIL I think @caspervanneck has to be a member of the organization to join I just checked the gitter permissions on the chat

**Comment by ISRAPIL** [comment]
Lol. one moment

**Comment by ISRAPIL** [comment]
Im create a public room 
check

**Comment by dancing-ipsum** [comment]
Hi

**Comment by ISRAPIL** [comment]
HELLO @MCPEGamerJPatGitHub

**Comment by Nought57** [comment]
gitter supported. please talk on gitter.

**Comment by Nought57** [comment]
Clear chat log bug.
