### ISSUE TITLE
[SPAM] Request

### ISSUE THREAD

**Issue by buchwasa** [ExtraCorePE/ExtraCorePE#10]
Hello ExtraCorePE, I've created a org to move all spoons of PM and Genisys, etc. and was wondering if you'd like to move ExtraCorePE there. You'd get full access to all repos, meaning you'd be owner, and you'd extra support from the rest of them team.

**Comment by QueryPE** [comment]
I think that is a good idea as long as all the ExtraCorePE Team gets to come and if @Nought57 wants to or not

**Comment by buchwasa** [comment]
The whole team gets to come.

**Comment by ISRAPIL** [comment]
Hi, I'm just fusing all the cores.

**Comment by ISRAPIL** [comment]
Hi, I like your idea, if you want to create one core. @AppleDevelops

**Comment by Nought57** [comment]
It seems that this plan has ended.

**Comment by Nought57** [comment]
Clear chat log bug.
