### ISSUE TITLE
Login timeout

### ISSUE THREAD

**Issue by atTheDisco** [ExtraCorePE/ExtraCorePE#11]
## Issues description
I'm trying to join the server. It says me "Login timeout" and on console says reason "Login timeout".
This problem does not happen everytime. Sometimes trying at 2nd and sometimes at 5th.
## Steps to reproduce the issue
Try to join the game, You will get this error

## OS and versions
* ExtraCorePE: this [commit](https://github.com/ExtraCorePE/ExtraCorePE/commit/1c9b20cc3fd6bca245a0ecc5f3ea2699f147b92b) 
* Game Version: 1.0.6
* Client Edition: pe/win10
* Server OS: lunix

## Detailed information files

> [ExtraCorePE] [15:34:52] INFO> Starting GS4 status listener
[ExtraCorePE] [15:34:52] INFO> Query running on 0.0.0.0:19132
[ExtraCorePE] [15:34:52] INFO> Default game type: Survival Mode
[ExtraCorePE] [15:34:52] INFO> Done (10.721s)! For help, type "help" or "?"
[ExtraCorePE] [15:35:27] INFO> Prisane[/192.168.1.6:19132] logged out due to timeout
[ExtraCorePE] [15:35:44] INFO> Prisane[/192.168.1.6:19132] logged out due to timeout
```

**Comment by QueryPE** [comment]
Please provide more imformation or this will be closed






## Issues description


## Steps to reproduce the issue


## OS and versions
* ExtraCorePE:
* Game Version: 
* Client Edition:
* Server OS:
* Server Host:


## Detailed information files
```

**Comment by atTheDisco** [comment]
I edited.

**Comment by Nought57** [comment]
Because it correspond to sound, there seems to be a case that the login time becomes long, and the server erroneously judges as Timeout. I'm going to relax Timeout's judgment.

**Comment by atTheDisco** [comment]
I think the problem is resolved, thx. But occasionally I get a "unable to connect to world" error. @Nought57

**Comment by atTheDisco** [comment]
and sometimes I get "Disconnect from the Server" error.

**Comment by ISRAPIL** [comment]
logged out due to timeout

**Comment by ISRAPIL** [comment]
Don't fixed

**Comment by Nought57** [comment]
@Prisane 1.0.7 login problem, fix it soon.

**Comment by ISRAPIL** [comment]
On my server it runs from 1.0.5 to 1.0.7. I'm use my old core of mine, you made a mistake somewhere ... @Prisane @Nought57

**Comment by Nought57** [comment]
@Prisane Resourcepack related timeout bug fixed.
Sound related bugs have also been fixed and you can log in faster than ever.

**Comment by ghost** [comment]
@Nought57 its a pureperms bug maby downgrade pure perms

**Comment by atTheDisco** [comment]
Okey thanks, i will try to.  @caspervanneck Is not related to pureperms. I have no plugin on my server

**Comment by Nought57** [comment]
Since the server has been fixed, if the timeout continues, look at the plugin.
