### ISSUE TITLE
getValue() on null

### ISSUE THREAD

**Issue by atTheDisco** [ExtraCorePE/ExtraCorePE#13]
## Issues description
`CRITICAL> Could not tick level "world": Call to a member function getValue() on null`
Constantly spamming the console
When this happens error it isn't doing teleport to the world. I'm sticking around. I can not move.

## OS and versions

* ExtraCorePE Version: [d54df39](https://github.com/ExtraCorePE/ExtraCorePE/commit/d54df3946342e5dd4e709d171d295727d96560a8)

* Game Version: 1.0.7

* Client Edition: pe/win10

* Server OS: lunix

## Detailed information files

```
ExtraCorePE Crash Dump Sun Apr 30 07:30:02 EEST 2017

Error: Call to a member function getValue() on null
File: /src/pocketmine/entity/Effect
Line: 305
Type: notice

Code:
[296] 			case Effect::INVISIBILITY:
[297] 				$entity->setDataFlag(Entity::DATA_FLAGS, Entity::DATA_FLAG_INVISIBLE, true);
[298] 				$entity->setNameTagVisible(false);
[299] 				break;
[300] 			case Effect::SPEED:
[301] 				$attr = $entity->getAttributeMap()->getAttribute(Attribute::MOVEMENT_SPEED);
[302] 				if($modify and $oldEffect !== null){
[303] 					$speed = $attr->getValue() / (1 + 0.2 * $oldEffect->getAmplifier());
[304] 				}else{
[305] 					$speed = $attr->getValue();
[306] 				}
[307] 				$speed *= (1 + 0.2 * $this->amplifier);
[308] 				$attr->setValue($speed);
[309] 				break;
[310] 			case Effect::SLOWNESS:
[311] 				$attr = $entity->getAttributeMap()->getAttribute(Attribute::MOVEMENT_SPEED);
[312] 				if($modify and $oldEffect !== null){
[313] 					$speed = $attr->getValue() / (1 - 0.15 * $oldEffect->getAmplifier());
[314] 				}else{
[315] 					$speed = $attr->getValue();

**Comment by ISRAPIL** [comment]
Line 162: 	self::$list[self::GOLD_AXE] = GoldAxe::class;

**Comment by atTheDisco** [comment]
Console is constantly sending spam, It's annoying. If @Nought57 fix the problem, I'd be happy.

**Comment by Nought57** [comment]
@Prisane I need more information. I feel that plugin is the cause.

**Comment by Prisane** [comment]
I do not think so, there is no such problem in the current version of Tesseract.

**Comment by atTheDisco** [comment]
It is not clear what the source of the problem is. The console only issues a "get Value () on null" error.

**Comment by Nought57** [comment]
Hmm, I will investigate in detail.

**Comment by Prisane** [comment]
@Nought57 The same problem with [Tesseract 120](https://github.com/TesseractTeam/Tesseract/issues/120)

**Comment by Nought57** [comment]
@Prisane This bug already fixed.

**Comment by Nought57** [comment]
It occurs when Chunk transmission is not done when doing tp.
Please change the setting of Chunk transmission

**Comment by Nought57** [comment]
It occurs when Chunk transmission is not done when doing tp.
Please change the setting of Chunk transmission.

**Comment by atTheDisco** [comment]
When this happens error it isn't doing teleport to the world. I'm sticking around. I can not move. After kick myself and console get `ERROR> Error while unloading a chunk: Call to a member function nbtSerialize() on null CRITICAL> Error: "Call to a member function nbtSerialize() on null" (EXCEPTION) in "/src/pocketmine/entity/Item" at line 162` error

**Comment by Nought57** [comment]
After kick and Console get error? This is important information to reproduce the bug. (Steps to reproduce the issue report item) From these information bugs are fixed smoothly.

**Comment by atTheDisco** [comment]
This morning, for this reason my server crash it. I edited issue.

**Comment by Nought57** [comment]
I know, Fix memory cause new error. fix it soon.

**Comment by Nought57** [comment]
Thanks Report!

**Comment by atTheDisco** [comment]
I will test it and saying improve. Thanks for helping me.

**Comment by atTheDisco** [comment]
@Nought57 I get this error
 `[ExtraCorePE] [2:57 pm] CRITICAL> Error: "Call to undefined method pocketmine\event\entity\EntityEffectAddEvent::willModify()" (EXCEPTION) in "/src/pocketmine/entity/Effect" at line 401`

**Comment by Nought57** [comment]
Correction was done with the latest version, please check whether a bug occurs.

**Comment by atTheDisco** [comment]
I solved the problem. it's all Beacon's fault... #26
