### ISSUE TITLE
Request to Help

### ISSUE THREAD

**Issue by Rateek** [ExtraCorePE/ExtraCorePE#16]
Possible to come help? For ExtraCore?

**Comment by QueryPE** [comment]
Do you want to help with ExtraCorePE?

**Comment by Rateek** [comment]
yes @QueryPE

**Comment by QueryPE** [comment]
@RateekMCPE contact us [here](https://gitter.im/ExtraCorePE/ExtraCorePE), @Nought57 is the owner of this so it is up to him to add you or not

**Comment by Nought57** [comment]
@RateekMCPE I sent an invitation. You can join ExtraCorePE organization.
