### ISSUE TITLE
Player online query not work

### ISSUE THREAD

**Issue by atTheDisco** [ExtraCorePE/ExtraCorePE#17]
## Issues description
```
[ExtraCorePE] [6:40 pm] INFO> Prisane[/192.168.0.11:57808] [ClientID: 5831241241418966] logged in with entity id 1 at (world, 256, 47, 256)
```
I login my server, server list in main menu is not updated. But in game "/list" working. Also Console information headers not working.

## OS and versions
* ExtraCorePE Version: [617f936](https://github.com/ExtraCorePE/ExtraCorePE/commit/617f9361215671f3ce9f16f20eae5906319191af)
* Game Version: 1.0.7
* Client Edition: pe/win10
* Server OS: lunix
## Detailed information files
Console information headers not working.
![1](https://cloud.githubusercontent.com/assets/13530796/25494793/89a81fc6-2b83-11e7-8477-73bac5b9a243.PNG)
![2](https://cloud.githubusercontent.com/assets/13530796/25494796/8bc50fb2-2b83-11e7-8916-5d75438902aa.PNG)

**Comment by Erkam246** [comment]
I know why: titletick isnt used...
![screenshot 7](https://cloud.githubusercontent.com/assets/16340573/25534106/16d1a03e-2c33-11e7-85fb-78a3ead1c6b0.png)

**Comment by xISRAPILx** [comment]
What? @erkam2002

**Comment by Erkam246** [comment]
Look at the picture titletick is for console header but its not used
