### ISSUE TITLE
Newest version cant start server

### ISSUE THREAD

**Issue by Erkam246** [ExtraCorePE/ExtraCorePE#21]
./start.sh
[ExtraCorePE] [1:22 pm] CRITICAL> Unable to find the Zip (zip) extension.
[ExtraCorePE] [1:22 pm] CRITICAL> Please use the installer provided on the homepage, or recompile PHP again.

It worked on https://github.com/ExtraCorePE/ExtraCorePE/tree/7a5c78eadb4495a021d328ba027cace0e980114e    this

**Comment by Nought57** [comment]
Commit 86-96 is Beta release. Please update start.sh file.

**Comment by erkam2002** [comment]
I updated already

**Comment by Erkam246** [comment]
I use php-build-script from ITXTech porblem is in PocketMine.php

**Comment by Erkam246** [comment]
Can you revert the changes on PocketMine.php?
