### ISSUE TITLE
Effect Problems

### ISSUE THREAD

**Issue by atTheDisco** [ExtraCorePE/ExtraCorePE#22]
## Issues description
New "effect" has new problem. addEffect and removeEffect functions not working. "/effect" command does not work

## OS and versions

* ExtraCorePE Version: [d54df39](https://github.com/ExtraCorePE/ExtraCorePE/commit/d54df3946342e5dd4e709d171d295727d96560a8)

* Game Version: 1.0.7

* Client Edition: pe/win10

* Server OS: lunix

## Detailed information files

```
[ExtraCorePE] [5:04 pm] CRITICAL> Unhandled exception executing command 'effect prisane 13 64' in effect: Call to undefined method pocketmine\event\entity\EntityEffectAddEvent::willModify()
[ExtraCorePE] [5:04 pm] CRITICAL> Error: "Call to undefined method pocketmine\event\entity\EntityEffectAddEvent::willModify()" (EXCEPTION) in "/src/pocketmine/entity/Effect" at line 401

**Comment by atTheDisco** [comment]
> [ExtraCorePE] [6:27 pm] CRITICAL> Unhandled exception executing command 'effect prisane clear' in effect: Argument 2 passed to pocketmine\event\entity\EntityEffectRemoveEvent::__construct() must be of the type integer, object given, called in /root/prs/src/pocketmine/entity/Effect.php on line 467
> [ExtraCorePE] [6:27 pm] CRITICAL> TypeError: "Argument 2 passed to pocketmine\event\entity\EntityEffectRemoveEvent::__construct() must be of the type integer, object given, called in /root/prs/src/pocketmine/entity/Effect.php on line 467" (EXCEPTION) in "/src/pocketmine/event/entity/EntityEffectRemoveEvent" at line 36
> 

removeEffect functions not working. @Nought57

**Comment by Erkam246** [comment]
CRITICAL> Could not tick level "Lobby": Class pocketmine\entity\EntityEffectRemoveEvent not found
[ExtraCorePE] [9:15 am] CRITICAL> Unhandled exception executing command 'effect mc clear' in effect: Class pocketmine\entity\EntityEffectRemoveEvent not found
[ExtraCorePE] [9:15 am] CRITICAL> ClassNotFoundException: "Class pocketmine\entity\EntityEffectRemoveEvent not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144


error on /effect clear

**Comment by atTheDisco** [comment]
Fixed.
