### ISSUE TITLE
[Request] add /ping command

### ISSUE THREAD

**Issue by atTheDisco** [ExtraCorePE/ExtraCorePE#27]
## Issues description
I cannot see any reason to do not add

**Comment by xISRAPILx** [comment]
I can add the function getPing().

**Comment by atTheDisco** [comment]
Okey, why not.

**Comment by Nought57** [comment]
TitleTick support soon.

**Comment by Nought57** [comment]
TitleTick ping support soon.

**Comment by Nought57** [comment]
Sry,  want to update frequently, but it does not work properly due to script and lag relationships. There is a possibility of adding in the future update.
