### ISSUE TITLE
[Request] add Map Item

### ISSUE THREAD

**Issue by atTheDisco** [ExtraCorePE/ExtraCorePE#28]
## Issues description
I lost my way. I need a map xd

**Comment by Erkam246** [comment]
This need to be closed or not?

**Comment by xISRAPILx** [comment]
Not.

**Comment by xISRAPILx** [comment]
Not. @erkam2002

**Comment by Nought57** [comment]
These are very heavy. Please use the function of Map with plugin. In the future we may add useful functions.
