### ISSUE TITLE
Throw bottle = Enderperl 

### ISSUE THREAD

**Issue by Erkam246** [ExtraCorePE/ExtraCorePE#30]
## OS and versions

* ExtraCorePE Version: Newest

* Game Version: 1.0.7

* Client Edition: Windows 10

* Server OS: Linux

* Server Host: Root Server

## Detailed information files
![trankender](https://cloud.githubusercontent.com/assets/16340573/25612153/e76b5c32-2f29-11e7-96c3-4b8e4bb4f0b0.gif)

**Comment by xISRAPILx** [comment]
LoL what
