### ISSUE TITLE
Mysql dont work

### ISSUE THREAD

**Issue by Erkam246** [ExtraCorePE/ExtraCorePE#31]

**Comment by xISRAPILx** [comment]
Plugin ISSUE or Binary ISSUE. Everything works. MySQL is independent of the kernel. @erkam2002

**Comment by Erkam246** [comment]
no.. if i use tesseract it work but if i use ECPE then not

**Comment by Nought57** [comment]
It's very strange. Mysql plugin successfully working.

**Comment by xISRAPILx** [comment]
This is not a kernel bug, everything has been verified!
