### ISSUE TITLE
Bows not work

### ISSUE THREAD

**Issue by atTheDisco** [ExtraCorePE/ExtraCorePE#32]
## Issues description
Bows not working, no arrow is thrown from bow

## Steps to reproduce the issue
Just try to shoot an arrow

## OS and versions

* ExtraCorePE Version: [4868cae](https://github.com/ExtraCorePE/ExtraCorePE/commit/4868cae4b7dcc581bda3cbf8229dbd63fe6da815)

* Game Version: 1.0.7

* Client Edition: pe/win10

* Server OS: lunix

**Comment by xISRAPILx** [comment]
Fixed!
![image](https://cloud.githubusercontent.com/assets/28113262/25659840/48a6a608-3012-11e7-83a5-58aa7c77f4d9.png)
