### ISSUE TITLE
Chat not work

### ISSUE THREAD

**Issue by Erkam246** [ExtraCorePE/ExtraCorePE#33]
## OS and versions

* ExtraCorePE Version: Newest

* Game Version: 1.0.7

* Client Edition: Windows 10

* Server OS: Linux

* Server Host: Root Server

## Detailed information files
```
Write in chat other players and i dont get the message only the console.

**Comment by xISRAPILx** [comment]
Do you use plugins to change the chat? Everything is fine on my server!

**Comment by Erkam246** [comment]
Can you join my server ? DimensionsPE.net

**Comment by xISRAPILx** [comment]
Ok

**Comment by Erkam246** [comment]
```
public function onPreCommand(PlayerCommandPreprocessEvent $event){
        $player = $event->getPlayer();
        $cmd = explode(" ", strtolower($event->getMessage()));
        if($cmd[0] == "/help" or $cmd[0] == "/?"){
            $event->setCancelled(true);
            $this->help($player);
        }
        if($cmd[0] == "/version" or $cmd[0] == "/ver" or $cmd[0] == "/about"){
            $event->setCancelled(true);
            $player->sendMessage("-= Server Info =-");
            $player->sendMessage(C::BLUE."DimensionsPE Network Software made by MCPEExpert".C::GRAY.".");
        }
        if($cmd[0] == "/me" or $cmd[0] == "/list"){
            $event->setCancelled(true);
        }
    }

**Comment by xISRAPILx** [comment]
Strange, on my server everything is fine... @erkam2002

**Comment by Erkam246** [comment]
What is the problem?

**Comment by Erkam246** [comment]
With tesseract work it fine

**Comment by xISRAPILx** [comment]
Use it @erkam2002 
```
if($cmd{0} != "/"){
return false;
}
```

**Comment by Erkam246** [comment]
?

**Comment by xISRAPILx** [comment]
@erkam2002 Use it, please
```
public function onPreCommand(PlayerCommandPreprocessEvent $event){
        $player = $event->getPlayer();
        $cmd = explode(" ", strtolower($event->getMessage()));
         if($cmd{0} != "/"){
                return false;
        }
        if($cmd[0] == "/help" or $cmd[0] == "/?"){
            $event->setCancelled(true);
            $this->help($player);
        }
        if($cmd[0] == "/version" or $cmd[0] == "/ver" or $cmd[0] == "/about"){
            $event->setCancelled(true);
            $player->sendMessage("-= Server Info =-");
            $player->sendMessage(C::BLUE."DimensionsPE Network Software made by MCPEExpert".C::GRAY.".");
        }
        if($cmd[0] == "/me" or $cmd[0] == "/list"){
            $event->setCancelled(true);
        }
    }
```

**Comment by Erkam246** [comment]
Ok

**Comment by xISRAPILx** [comment]
I am waiting... @erkam2002

**Comment by Erkam246** [comment]
Can you add Void generator?

**Comment by xISRAPILx** [comment]
What?

**Comment by Erkam246** [comment]
Chat dont work

**Comment by Erkam246** [comment]
I mean can you add the Void generator with 1 block

**Comment by xISRAPILx** [comment]
Hmm, strange, you do not exactly use PlayerСhatEvent? @erkam2002

**Comment by QueryPE** [comment]
@xISRAPILx I know how to fix this with a plugin but I have looked into this and I do not understand why this is happening

**Comment by Erkam246** [comment]
It works with Tesseract...

**Comment by xISRAPILx** [comment]
On my server, everything is fine. @erkam2002

**Comment by xISRAPILx** [comment]
Upgrade the kernel to the latest version @erkam2002

**Comment by Erkam246** [comment]
kernel?

**Comment by Erkam246** [comment]
You mean ExtraCorePE?

**Comment by QueryPE** [comment]
I added this to my server, and it fixed the chat bug as a temp fix

Only issue is this does not allow multi world chat and does not fix console
```
  public function myChatFixLol(\pocketmine\event\player\PlayerChatEvent $e){
    $player = $e->getPlayer();
    $level = $player->getLevel();
    $e->setRecipients($player->getLevel()->getPlayers());
  }
```

**Comment by Erkam246** [comment]
I think its another problem @thebigsmilexD was on my server and he write anything with % and then has the chat no longer worked..

**Comment by xISRAPILx** [comment]
Upgrade the kernel to the latest version @erkam2002

**Comment by Erkam246** [comment]
What is kernel????

**Comment by Erkam246** [comment]
LOL with the code of @QueryPE work it :D

**Comment by Erkam246** [comment]
But the message with not shown in CONSOLE -.-

**Comment by QueryPE** [comment]
I know

**Comment by QueryPE** [comment]
I will look into this more

**Comment by Erkam246** [comment]
Have you the same problem?

**Comment by QueryPE** [comment]
I do, but there could be a plugin causing it on your server as well as mine

**Comment by QueryPE** [comment]
I am not sure but I am guessing

**Comment by Erkam246** [comment]
I have only my core plugin and ManyWorld and MagicWE....

**Comment by QueryPE** [comment]
I am going to look into this, I shall do my best

**Comment by inxomnyaa** [comment]
@erkam2002 whoops xd %pocketmine.server.version%

**Comment by Nought57** [comment]
I  knew this bug. but, A bug occurs even though I haven't made any major changes. API 4.0.0 was incomplete. However, I have created these in anticipation of functional improvement. These bugs bother me. I will keep looking for the cause.

**Comment by QueryPE** [comment]
I fixed pushing in a few minutes

**Comment by Nought57** [comment]
Some problem, online query etc.

**Comment by QueryPE** [comment]
somehow a line like this got removed

```

		if($this->hasPermission(Server::BROADCAST_CHANNEL_USERS)){
			$this->server->getPluginManager()->subscribeToPermission(Server::BROADCAST_CHANNEL_USERS, $this);
		}
```

**Comment by Nought57** [comment]
Delete some channel function soon.

**Comment by QueryPE** [comment]
Fixed @Nought57 @erkam2002 

![screenshot from 2017-05-03 06-25-49](https://cloud.githubusercontent.com/assets/26948923/25662434/626f991c-2fc9-11e7-82d2-b1868814f249.png)

**Comment by Nought57** [comment]
Need channel function?

**Comment by QueryPE** [comment]
I do not know

**Comment by Nought57** [comment]
I will remove it. Because, Chat has frequent updates, so they can also cause lag.

**Comment by QueryPE** [comment]
Just dont break things XD

**Comment by Nought57** [comment]
Hmm, many src use channel function.
