### ISSUE TITLE
[QUESTION] Blocking Third Party Client 

### ISSUE THREAD

**Issue by atTheDisco** [ExtraCorePE/ExtraCorePE#38]
## Issues description
Do I only have a chance to host the players who use the vanilla client?

**Comment by Erkam246** [comment]
You mean hack clients?

**Comment by atTheDisco** [comment]
Yes.

**Comment by Erkam246** [comment]
I think no. But you can block Windows or IOS or Android

**Comment by Nought57** [comment]
It is difficult to confirmation. There is no choice but to check using Packet etc. but, You can not prevent them completely even if you use them. By limiting the data to send, hack client can be prevented.

**Comment by atTheDisco** [comment]
I understand, so is there a method or function?

**Comment by xISRAPILx** [comment]
I tried, all the cheat clients use the default client.
