### ISSUE TITLE
Water Bug

### ISSUE THREAD

**Issue by atTheDisco** [ExtraCorePE/ExtraCorePE#40]
## Issues description
Water is auto forming in the air. This event repeats itself

## OS and versions

* ExtraCorePE Version: [45ec8fe](https://github.com/ExtraCorePE/ExtraCorePE/commit/45ec8fe9a71a06d7b9cf3d9590bd37d73da91e92)

* Game Version: 1.0.8

* Client Edition: pe/win10

* Server OS: lunix

## Detailed information files
![adsiz](https://cloud.githubusercontent.com/assets/13530796/25910648/b981e82c-35b9-11e7-96ac-b5826dac4a8f.png)
```

**Comment by Erkam246** [comment]
Was me too
