### ISSUE TITLE
Ban command not work

### ISSUE THREAD

**Issue by Erkam246** [ExtraCorePE/ExtraCorePE#41]
## Issues description
Ban cause critical error

## Steps to reproduce the issue
/ban (player name)

## OS and versions

* ExtraCorePE Version: Newest

* Game Version: 1.0.8

* Client Edition: Windows 10

* Server OS: Linux 

* Server Host: Root Server

## Detailed information files
```
CRITICAL> Unhandled exception executing command 'ban Anstronautii' in ban: Class
pocketmine\command\defaults\date not found

**Comment by ghost** [comment]
Can someone please tell me if this has a similar API to pmmp.io?
