### ISSUE TITLE
I want to make a pull request with Github Destop but i cant make pull requests with it only to another branch! Need Help

### ISSUE THREAD

**Issue by Erkam246** [ExtraCorePE/ExtraCorePE#46]

**Comment by xISRAPILx** [comment]
I do not understand ...

**Comment by Erkam246** [comment]
I cant tap on send pullrequest button but if change the branch then can i tap

I will send a video later

**Comment by Erkam246** [comment]
![git](https://cloud.githubusercontent.com/assets/16340573/26648965/7038e990-4644-11e7-9fa0-6454aaf72916.gif)
???

**Comment by erkam2002** [comment]
# Hi1
## Hi2
### Hi3
#### Hi4
##### Hi5
###### Hi6

**Comment by xISRAPILx** [comment]
Hmm... @erkam2002

**Comment by Erkam246** [comment]
?

**Comment by xISRAPILx** [comment]
Don't know... @erkam2002
