### ISSUE TITLE
Sync pack error

### ISSUE THREAD

**Issue by ghost** [ExtraCorePE/ExtraCorePE#50]
Impossible to connect  to server
![screenshot_2017-06-02-08-38-00](https://cloud.githubusercontent.com/assets/25569806/26713940/4d00fb94-476f-11e7-923b-cb35f399713f.png)
![screenshot_2017-06-02-08-40-03](https://cloud.githubusercontent.com/assets/25569806/26713943/513e664c-476f-11e7-9bac-d79ffe142ee7.png)

**Comment by xISRAPILx** [comment]
Use the latest kernel version. Do you use the package of texture packs sending? @armagadon159753

**Comment by ghost** [comment]
I use last version in SRC package or Phar package i have the same error.
I Nevers use Texture Pack.

**Comment by Nought57** [comment]
1.1.0 doesn't support yet. update soon.

**Comment by ghost** [comment]
I will be patient ^•^
