### ISSUE TITLE
motd not work

### ISSUE THREAD

**Issue by DanilZz** [ExtraCorePE/ExtraCorePE#52]
## OS and versions

* ExtraCorePE Version:

* Game Version: 1.0.5 and 1.0.7

* Client Edition: null

* Server OS: Lunux

* Server Host: VPS

## Detailed information files
```
Motd not show on minecraft servers list

**Comment by xISRAPILx** [comment]
Всё работает, только количество не показывает. @DanilZz 

![image](https://cloud.githubusercontent.com/assets/28113262/26752604/56d84940-485c-11e7-92ed-fd02d74706ed.png)

**Comment by DanilZz** [comment]
Даже не показывает
