### ISSUE TITLE
I need phar

### ISSUE THREAD

**Issue by vwscripts** [ExtraCorePE/ExtraCorePE#57]

**Comment by Erkam246** [comment]
you use too src

**Comment by vwscripts** [comment]
i cant my server dont load with only src

**Comment by Erkam246** [comment]
switch your start.sh

**Comment by xISRAPILx** [comment]
Everything will be fine! Now I have a development time. @erkam2002 @ivan691 @

**Comment by Erkam246** [comment]
ok

**Comment by Nought57** [comment]
I'm considering preparing a phar with a stable version. But, ExtraCorePE is not yet compatible with 1.1.0, Therefore, there is no corresponding phar yet. Please wait for a while until correspondence.
