### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by dancing-ipsum** [ExtraCorePE/ExtraCorePE#6]
Resourcepacks & general commands builtin are broken (unknown command と表示する)

**Comment by Nought57** [comment]
We are currently investigating Resource Pack.
Please give detailed information on general commands are broken problem.*

**Comment by Nought57** [comment]
We are currently investigating Resource Pack.
Please give detailed information on general commands are broken problem.

**Comment by Nought57** [comment]
thanks, I will trying fix.

**Comment by ISRAPIL** [comment]
Please give detailed information on general commands are broken problem.

**Comment by Nought57** [comment]
Sry, Bugs could not be confirmed, if there seems to be a bug, I created a template, please fill in that and submit your issue again.

**Comment by Nought57** [comment]
Clear chat log bug.
