### ISSUE TITLE
Login timeout

### ISSUE THREAD

**Issue by lowingly** [ExtraCorePE/ExtraCorePE#8]
I can not enter the server------ login timeout.

[ExtraCorePE] [2:33 pm] CRITICAL> Error: "Call to undefined method pocketmine\Server::getResourcePackManager()" (EXCEPTION) in "/src/pocketmine/Player" at line 2101
[ExtraCorePE] [2:33 pm] INFO> lolita[/192.168.0.12:19132] logged out due to Login timeout

本服务器正运行 ExtraCorePE-1.0.0 (代号 "Soleil")
 PHP 版本: 7.0.8
API: 4.0.0 (iTX API 版本 {%1})
客户端: Minecraft PE v1.0.5 (protocol 版本
Protocol version: 105

**Comment by QueryPE** [comment]
@Nought57 there is no `getResourcePackManager` function in Server.php

**Comment by QueryPE** [comment]
@Nought57 did you make a typo [here](https://github.com/ExtraCorePE/ExtraCorePE/blob/master/src/pocketmine/Server.php#L631)?

**Comment by Nought57** [comment]
I will fix it soon.

**Comment by Nought57** [comment]
Sry, It is my mistake. I will fix it soon.
All are unified with getResourceManager

**Comment by Nought57** [comment]
Sry, It is my mistake. I will fix it soon.
All are unified with getResourcePackManager.
