### ISSUE TITLE
Trapped Chest

### ISSUE THREAD

**Issue by lowingly** [ExtraCorePE/ExtraCorePE#9]
Creation model:
Set a Trapped Chest, and Open it.

Notice: Undefined property: pocketmine\Server::$limitedCreative in C:\Users\COCOD\Desktop\Ex\src\pocketmine\block\TrappedChest.php on line 185

And...
I still have a problem：
Now create mode can open the Chest? I remember that I could not open the Chest before...

517c2b1
window7
php7

**Comment by Nought57** [comment]
It seems that the setting to open chest is broken, so please wait until the correction.
